// <auto-generated />
using System;
using Cine_Lumia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine_Lumia.Migrations
{
    [DbContext(typeof(CineDbContext))]
    [Migration("20251108083518_RevertToNombreApellidoAndAddAvatar")]
    partial class RevertToNombreApellidoAndAddAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine_Lumia.Entities.Asiento", b =>
                {
                    b.Property<int>("Id_Asiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Asiento"));

                    b.Property<int>("Columna")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Id_Sala")
                        .HasColumnType("int");

                    b.HasKey("Id_Asiento");

                    b.HasIndex("Id_Sala");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Cine", b =>
                {
                    b.Property<int>("Id_Cine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cine"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Cine");

                    b.HasIndex("Id_Empresa");

                    b.ToTable("Cines");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.CineConsumible", b =>
                {
                    b.Property<int>("Id_Cine")
                        .HasColumnType("int");

                    b.Property<int>("Id_Consumible")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id_Cine", "Id_Consumible");

                    b.HasIndex("Id_Consumible");

                    b.ToTable("CineConsumibles");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Consumible", b =>
                {
                    b.Property<int>("Id_Consumible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Consumible"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Consumible");

                    b.ToTable("Consumibles");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Empresa", b =>
                {
                    b.Property<int>("Id_Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empresa"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Empresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Entrada", b =>
                {
                    b.Property<int>("Id_Entrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Entrada"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Asiento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Espectador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proyeccion")
                        .HasColumnType("int");

                    b.Property<int>("Id_TipoEntrada")
                        .HasColumnType("int");

                    b.HasKey("Id_Entrada");

                    b.HasIndex("Id_Asiento");

                    b.HasIndex("Id_Espectador");

                    b.HasIndex("Id_Proyeccion");

                    b.HasIndex("Id_TipoEntrada");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Espectador", b =>
                {
                    b.Property<int>("Id_Espectador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Espectador"));

                    b.Property<string>("Alias")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdAvatar")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id_Espectador");

                    b.ToTable("Espectadores");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.EspectadorConsumible", b =>
                {
                    b.Property<int>("Id_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Compra"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Cine")
                        .HasColumnType("int");

                    b.Property<int>("Id_Consumible")
                        .HasColumnType("int");

                    b.Property<int>("Id_Espectador")
                        .HasColumnType("int");

                    b.HasKey("Id_Compra");

                    b.HasIndex("Id_Cine");

                    b.HasIndex("Id_Consumible");

                    b.HasIndex("Id_Espectador");

                    b.ToTable("EspectadorConsumibles");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Formato", b =>
                {
                    b.Property<int>("Id_Formato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Formato"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Formato");

                    b.ToTable("Formato");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Genero", b =>
                {
                    b.Property<int>("Id_Genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Genero"));

                    b.Property<string>("GeneroNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Genero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Pelicula", b =>
                {
                    b.Property<int>("Id_Pelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pelicula"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Estreno")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Pelicula");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.PeliculaGenero", b =>
                {
                    b.Property<int>("Id_Pelicula")
                        .HasColumnType("int");

                    b.Property<int>("Id_Genero")
                        .HasColumnType("int");

                    b.HasKey("Id_Pelicula", "Id_Genero");

                    b.HasIndex("Id_Genero");

                    b.ToTable("PeliculaGeneros");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Proyeccion", b =>
                {
                    b.Property<int>("Id_Proyeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proyeccion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("Id_Pelicula")
                        .HasColumnType("int");

                    b.Property<int>("Id_Sala")
                        .HasColumnType("int");

                    b.HasKey("Id_Proyeccion");

                    b.HasIndex("Id_Pelicula");

                    b.HasIndex("Id_Sala");

                    b.ToTable("Proyecciones");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Sala", b =>
                {
                    b.Property<int>("Id_Sala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Sala"));

                    b.Property<int>("Cant_Butacas")
                        .HasColumnType("int");

                    b.Property<int>("Cant_Filas")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Cine")
                        .HasColumnType("int");

                    b.Property<int>("Id_Formato")
                        .HasColumnType("int");

                    b.HasKey("Id_Sala");

                    b.HasIndex("Id_Cine");

                    b.HasIndex("Id_Formato");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.TipoEntrada", b =>
                {
                    b.Property<int>("Id_TipoEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TipoEntrada"));

                    b.Property<int>("Id_Formato")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_TipoEntrada");

                    b.HasIndex("Id_Formato");

                    b.ToTable("TipoEntrada");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Asiento", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Sala", "Sala")
                        .WithMany("Asientos")
                        .HasForeignKey("Id_Sala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Cine", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Empresa", "Empresa")
                        .WithMany("Cines")
                        .HasForeignKey("Id_Empresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.CineConsumible", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Cine", "Cine")
                        .WithMany("CineConsumibles")
                        .HasForeignKey("Id_Cine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Consumible", "Consumible")
                        .WithMany("CineConsumibles")
                        .HasForeignKey("Id_Consumible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cine");

                    b.Navigation("Consumible");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Entrada", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Asiento", "Asiento")
                        .WithMany("Entradas")
                        .HasForeignKey("Id_Asiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Espectador", "Espectador")
                        .WithMany("Entradas")
                        .HasForeignKey("Id_Espectador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Proyeccion", "Proyeccion")
                        .WithMany("Entradas")
                        .HasForeignKey("Id_Proyeccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.TipoEntrada", "TipoEntrada")
                        .WithMany("Entradas")
                        .HasForeignKey("Id_TipoEntrada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Espectador");

                    b.Navigation("Proyeccion");

                    b.Navigation("TipoEntrada");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.EspectadorConsumible", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Cine", "Cine")
                        .WithMany("EspectadorConsumibles")
                        .HasForeignKey("Id_Cine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Consumible", "Consumible")
                        .WithMany("EspectadorConsumibles")
                        .HasForeignKey("Id_Consumible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Espectador", "Espectador")
                        .WithMany("EspectadorConsumibles")
                        .HasForeignKey("Id_Espectador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cine");

                    b.Navigation("Consumible");

                    b.Navigation("Espectador");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.PeliculaGenero", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Genero", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("Id_Genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Pelicula", "Pelicula")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("Id_Pelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Proyeccion", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Pelicula", "Pelicula")
                        .WithMany("Proyecciones")
                        .HasForeignKey("Id_Pelicula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Sala", "Sala")
                        .WithMany("Proyecciones")
                        .HasForeignKey("Id_Sala")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Sala", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Cine", "Cine")
                        .WithMany("Salas")
                        .HasForeignKey("Id_Cine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine_Lumia.Entities.Formato", "Formato")
                        .WithMany("Salas")
                        .HasForeignKey("Id_Formato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cine");

                    b.Navigation("Formato");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.TipoEntrada", b =>
                {
                    b.HasOne("Cine_Lumia.Entities.Formato", "Formato")
                        .WithMany("TipoEntradas")
                        .HasForeignKey("Id_Formato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formato");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Asiento", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Cine", b =>
                {
                    b.Navigation("CineConsumibles");

                    b.Navigation("EspectadorConsumibles");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Consumible", b =>
                {
                    b.Navigation("CineConsumibles");

                    b.Navigation("EspectadorConsumibles");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Empresa", b =>
                {
                    b.Navigation("Cines");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Espectador", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("EspectadorConsumibles");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Formato", b =>
                {
                    b.Navigation("Salas");

                    b.Navigation("TipoEntradas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Genero", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Pelicula", b =>
                {
                    b.Navigation("PeliculaGeneros");

                    b.Navigation("Proyecciones");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Proyeccion", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.Sala", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Proyecciones");
                });

            modelBuilder.Entity("Cine_Lumia.Entities.TipoEntrada", b =>
                {
                    b.Navigation("Entradas");
                });
#pragma warning restore 612, 618
        }
    }
}
